"""Calendar data generator module - reads plans from LLM-generated world_state."""

from typing import Dict, Any, List


def generate_calendar_data(world_state: Dict[str, Any], calendar_plans: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Generate Google Calendar-like events from world_state and calendar_plans.
    Must conform to schemas/calendar_schema.json.
    
    The calendar_plans come from world_state.per_source_plans.calendar_plans,
    which are generated by the LLM based on the scenario.
    """
    scenario_id = world_state.get("scenario_id", "scenario_A")
    plans_count = len(calendar_plans)
    print(f"[calendar_generator] Start: scenario_id={scenario_id}, plans={plans_count}")
    
    # Build person lookup by ID
    people_by_id = {person["id"]: person for person in world_state.get("people", [])}
    
    events = []
    event_id = 1
    
    # Process each plan from LLM-generated per_source_plans
    for plan_idx, plan in enumerate(calendar_plans):
        # Progress logging every 10th plan
        if plan_idx > 0 and plan_idx % 10 == 0:
            print(f"[calendar_generator] Progress: {plan_idx}/{plans_count} plans processed")
        # Plans should contain: title, start, end, participants (person IDs)
        # The LLM is responsible for determining these based on the scenario
        
        title = plan.get("title", "Meeting")
        start = plan.get("start")  # ISO datetime string
        end = plan.get("end")  # ISO datetime string
        participant_ids = plan.get("participants", [])  # List of person IDs
        
        if not start or not end:
            # Skip plans without required timing info
            continue
        
        # Build attendees from participant IDs
        attendees = []
        for person_id in participant_ids:
            person = people_by_id.get(person_id, {})
            if person:
                attendees.append({
                    "email": person.get("email", ""),
                    "name": person.get("name", "")
                })
        
        if attendees:  # Only add events with at least one attendee
            events.append({
                "id": f"E{event_id}",
                "title": title,
                "start": start,
                "end": end,
                "attendees": attendees
            })
            event_id += 1
    
    # Create calendars for each person
    calendars = [
        {
            "id": person["id"],
            "email": person["email"]
        }
        for person in world_state.get("people", [])
    ]
    
    events_count = len(events)
    calendars_count = len(calendars)
    print(f"[calendar_generator] Result: events={events_count}, calendars={calendars_count}")
    
    return {
        "events": events,
        "calendars": calendars
    }
