"""Drive data generator module - reads plans from LLM-generated world_state."""

from typing import Dict, Any, List


def generate_drive_data(world_state: Dict[str, Any], drive_plans: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Generate Google Drive-like file metadata and simple text content
    from world_state and drive_plans.
    Must conform to schemas/drive_schema.json.
    
    The drive_plans come from world_state.per_source_plans.drive_plans,
    which are generated by the LLM based on the scenario.
    """
    files = []
    
    # Process each plan from LLM-generated per_source_plans
    for plan in drive_plans:
        # Plans should contain: id, name, mimeType, content (text excerpt), modifiedTime
        # The LLM is responsible for determining these based on the scenario
        
        file_id = plan.get("id", f"file_{len(files) + 1}")
        file_name = plan.get("name", "Document")
        mime_type = plan.get("mimeType", "application/octet-stream")
        content = plan.get("content", "")  # Text excerpt or content
        modified_time = plan.get("modifiedTime", "")  # ISO datetime string
        
        if not file_name:
            continue
        
        # Use modified_time from plan, or provide generic fallback if missing
        if not modified_time:
            modified_time = "2025-11-01T10:00:00+09:00"
        
        files.append({
            "id": file_id,
            "name": file_name,
            "mimeType": mime_type,
            "content": content,
            "modifiedTime": modified_time
        })
    
    return {
        "files": files
    }
