"""Gmail data generator module - reads plans from LLM-generated world_state."""

from typing import Dict, Any, List


def generate_gmail_data(world_state: Dict[str, Any], gmail_plans: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Generate Gmail-style data (threads and messages) from world_state and gmail_plans.
    Must conform to schemas/gmail_schema.json.
    
    The gmail_plans come from world_state.per_source_plans.gmail_plans,
    which are generated by the LLM based on the scenario.
    """
    threads = []
    thread_id = 1
    message_id = 1
    
    # Process each plan from LLM-generated per_source_plans
    for plan in gmail_plans:
        # Plans should contain: subject, messages (list with from, to, body, date)
        # The LLM is responsible for determining these based on the scenario
        
        subject = plan.get("subject", "Email Thread")
        plan_messages = plan.get("messages", [])
        
        if not plan_messages:
            continue
        
        # Convert plan messages to schema format
        thread_messages = []
        for msg_plan in plan_messages:
            thread_messages.append({
                "id": f"M{message_id}",
                "from": msg_plan.get("from", ""),
                "to": msg_plan.get("to", []),
                "subject": subject,
                "body": msg_plan.get("body", ""),
                "date": msg_plan.get("date", "")  # ISO datetime string
            })
            message_id += 1
        
        if thread_messages:
            threads.append({
                "id": f"T{thread_id}",
                "subject": subject,
                "messages": thread_messages
            })
            thread_id += 1
    
    return {
        "threads": threads
    }
