"""Propagation engine module - simplified to read per_source_plans from LLM-generated world_state."""

from typing import Dict, Any


def build_event_plans(world_state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Extract per_source_plans from world_state.
    
    The LLM-generated world_state already contains per_source_plans with all the
    necessary plans for each data source. This function simply extracts and returns them.
    
    Args:
        world_state: Dict containing per_source_plans (generated by LLM)
        
    Returns:
        Dict with keys: slack_plans, gmail_plans, calendar_plans, 
        contacts_plans, jira_plans, drive_plans. Each value is a list of plan dicts.
    """
    sub_scenarios_expanded_count = len(world_state.get("sub_scenarios_expanded", []))
    noise_scenarios_count = len(world_state.get("noise_scenarios", []))
    print(f"[propagation_engine] Start build_event_plans: sub_scenarios_expanded={sub_scenarios_expanded_count}, noise_scenarios={noise_scenarios_count}")
    
    # The LLM-generated world_state should contain per_source_plans
    per_source_plans = world_state.get("per_source_plans", {})
    
    # Ensure all required keys exist with empty lists as defaults
    plans = {
        "slack_plans": per_source_plans.get("slack_plans", []),
        "gmail_plans": per_source_plans.get("gmail_plans", []),
        "calendar_plans": per_source_plans.get("calendar_plans", []),
        "contacts_plans": per_source_plans.get("contacts_plans", []),
        "jira_plans": per_source_plans.get("jira_plans", []),
        "drive_plans": per_source_plans.get("drive_plans", []),
    }
    
    # Log plan counts
    slack_count = len(plans["slack_plans"])
    gmail_count = len(plans["gmail_plans"])
    calendar_count = len(plans["calendar_plans"])
    contacts_count = len(plans["contacts_plans"])
    jira_count = len(plans["jira_plans"])
    drive_count = len(plans["drive_plans"])
    print(f"[propagation_engine] Generated plans: slack={slack_count}, gmail={gmail_count}, calendar={calendar_count}, contacts={contacts_count}, jira={jira_count}, drive={drive_count}")
    
    plan_keys = list(plans.keys())
    print(f"[propagation_engine] Plan dict built with keys: {plan_keys}")
    
    return plans
