"""Propagation engine module - simplified to read per_source_plans from LLM-generated world_state."""

from typing import Dict, Any


def build_event_plans(world_state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Extract per_source_plans from world_state.
    
    The LLM-generated world_state already contains per_source_plans with all the
    necessary plans for each data source. This function simply extracts and returns them.
    
    Args:
        world_state: Dict containing per_source_plans (generated by LLM)
        
    Returns:
        Dict with keys: slack_plans, gmail_plans, calendar_plans, 
        contacts_plans, jira_plans, drive_plans. Each value is a list of plan dicts.
    """
    # The LLM-generated world_state should contain per_source_plans
    per_source_plans = world_state.get("per_source_plans", {})
    
    # Ensure all required keys exist with empty lists as defaults
    plans = {
        "slack_plans": per_source_plans.get("slack_plans", []),
        "gmail_plans": per_source_plans.get("gmail_plans", []),
        "calendar_plans": per_source_plans.get("calendar_plans", []),
        "contacts_plans": per_source_plans.get("contacts_plans", []),
        "jira_plans": per_source_plans.get("jira_plans", []),
        "drive_plans": per_source_plans.get("drive_plans", []),
    }
    
    return plans
